// <auto-generated />
namespace WPF_Calculator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_string));
        
        string IMigrationMetadata.Id
        {
            get { return "201702131912027_string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
